/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: 'var(--color-primary, #50644b)',
        'primary-dim': 'var(--color-primary-dim, #445840)',
        'primary-container': 'var(--color-primary-container, #d2e9c9)',
        'primary-fixed': 'var(--color-primary-fixed, #d0e9d6)',
        'primary-fixed-dim': 'var(--color-primary-fixed-dim, #b4ccbb)',
        'on-primary': 'var(--color-on-primary, #eaffe1)',
        'on-primary-container': 'var(--color-on-primary-container, #43573e)',
        secondary: '#c26d4a',
        'secondary-container': '#ffd9c2',
        'on-secondary-container': '#5c2f16',
        tertiary: '#a77c2e',
        'tertiary-container': '#ffe6b3',
        'tertiary-fixed-dim': '#f2d497',
        'on-tertiary-container': '#4d3710',
        error: '#b33a3a',
        'on-error': '#ffffff',
        surface: '#fdfbf5',
        'surface-container-low': '#f6f4ec',
        'surface-container': '#efede4',
        'surface-container-high': '#e8e6dc',
        'surface-container-highest': '#e0ded3',
        'on-surface': '#25271f',
        'on-surface-variant': '#4c4e45',
        'outline-variant': '#a8a89e',
        background: '#fdfbf5',
      },
      fontFamily: {
        headline: ['Noto Serif', 'Georgia', 'serif'],
        body: ['Manrope', 'system-ui', 'sans-serif'],
        label: ['Manrope', 'system-ui', 'sans-serif'],
        sans: ['Manrope', 'system-ui', 'sans-serif'],
        serif: ['Noto Serif', 'Georgia', 'serif'],
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
       'safe': 'env(safe-area-inset-top)',
      },
    },
  },
  plugins: [],
}